name: sscsw
channels:
    - ioos
dependencies:
    - python=2.7
    - bokeh
    - folium
    - jupyter
    - matplotlib
    - owslib
    - pandas
    - pyoos
    - pysgrid
    - pyugrid
    - gridgeo
